
export type JobMode = "Remote" | "Hybrid" | "Onsite";
export type JobExperience = "Fresher" | "0-1 Years" | "1-3 Years" | "3-5 Years" | "5+ Years";
export type JobSource = "LinkedIn" | "Naukri" | "Indeed" | "Company Site";

export type JobStatus = "Not Applied" | "Applied" | "Rejected" | "Selected";

export interface JobStatusRecord {
    status: JobStatus;
    updatedAt: string;
}

export interface Job {
    id: string;
    title: string;
    company: string;
    location: string;
    mode: JobMode;
    experience: JobExperience;
    skills: string[];
    source: JobSource;
    postedDaysAgo: number;
    salaryRange: string;
    applyUrl: string;
    description: string;
}

export const JOBS: Job[] = [
    // 1-10: Freshers / Interns
    {
        id: "j1",
        title: "SDE Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Go", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30,000/month",
        applyUrl: "#",
        description: "Join our payments team to build scalable financial infrastructure. You will work on high-throughput systems and learn from the best engineers in the industry.",
    },
    {
        id: "j2",
        title: "Frontend Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "CSS", "JavaScript"],
        source: "Company Site",
        postedDaysAgo: 1,
        salaryRange: "₹25,000/month",
        applyUrl: "#",
        description: "Work on the Swiggy consumer app. Responsible for building pixel-perfect UI components and optimizing performance for millions of users.",
    },
    {
        id: "j3",
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Communication"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "3.5 - 4.5 LPA",
        applyUrl: "#",
        description: "Excellent opportunity for fresh graduates to start their career with TCS. Training provided in latest technologies.",
    },
    {
        id: "j4",
        title: "Data Analyst Intern",
        company: "Cred",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "SQL", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹40,000/month",
        applyUrl: "#",
        description: "Analyze user behavior data to drive creditworthiness insights. High-impact role for those who love numbers.",
    },
    {
        id: "j5",
        title: "QA Intern",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Java"],
        source: "Company Site",
        postedDaysAgo: 3,
        salaryRange: "₹15,000/month",
        applyUrl: "#",
        description: "Ensure quality of Zoho's suite of apps. Learn automation testing frameworks and contribute to release cycles.",
    },
    {
        id: "j6",
        title: "Software Engineer Trainee",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C#", ".NET", "SQL"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "4 LPA",
        applyUrl: "#",
        description: "Join Wipro's digital transformation team. Training on cloud and backend technologies provided.",
    },
    {
        id: "j7",
        title: "Backend Intern",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Go", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹50,000/month",
        applyUrl: "#",
        description: "Work on the Kite trading platform. High performance and low latency are the key requirements.",
    },
    {
        id: "j8",
        title: "Product Design Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Figma", "UI/UX", "Prototyping"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹35,000/month",
        applyUrl: "#",
        description: "Design intuitive user flows for Flipkart's e-commerce platform. Mentorship from senior designers available.",
    },
    {
        id: "j9",
        title: "Associate Software Engineer",
        company: "Accenture",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Spring Boot", "AWS"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "4.5 - 6 LPA",
        applyUrl: "#",
        description: "Start your career with Accenture. Work on varied projects for global clients.",
    },
    {
        id: "j10",
        title: "Research Intern",
        company: "Microsoft Research India",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Machine Learning", "Python", "PyTorch"],
        source: "Company Site",
        postedDaysAgo: 2,
        salaryRange: "₹80,000/month",
        applyUrl: "#",
        description: "Work on cutting-edge AI research. Publish papers and contribute to open source models.",
    },

    // 11-30: 0-3 Years Experience (Junior/Mid)
    {
        id: "j11",
        title: "Junior Backend Developer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Java", "Dropwizard", "MySQL"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "12 - 18 LPA",
        applyUrl: "#",
        description: "Build robust payment gateways. Handle high concurrency and ensure 99.99% uptime.",
    },
    {
        id: "j12",
        title: "React Developer",
        company: "Meesho",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["React", "Redux", "Typescript"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "10 - 15 LPA",
        applyUrl: "#",
        description: "Scale Meesho's reseller platform. Focus on mobile-web performance and user engagement.",
    },
    {
        id: "j13",
        title: "Software Engineer I",
        company: "Uber",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1 Years",
        skills: ["Go", "Kafka", "Microservices"],
        source: "Company Site",
        postedDaysAgo: 1,
        salaryRange: "18 - 25 LPA",
        applyUrl: "#",
        description: "Join the Uber maps team. Solve complex logistical problems at scale.",
    },
    {
        id: "j14",
        title: "Python Developer",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "0-1 Years",
        skills: ["Python", "Django", "REST APIs"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "4 - 8 LPA",
        applyUrl: "#",
        description: "Develop internal tools and automation scripts. Good learning ground for backend development.",
    },
    {
        id: "j15",
        title: "Frontend Engineer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Ember.js", "Javascript", "HTML/CSS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "8 - 14 LPA",
        applyUrl: "#",
        description: "Build delightful SaaS interfaces for Freshdesk. Work in a fast-paced agile environment.",
    },
    {
        id: "j16",
        title: "Java Developer",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Java", "Spring", "Oracle DB"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "10 - 16 LPA",
        applyUrl: "#",
        description: "Work on Oracle Cloud Infrastructure. Deep dive into distributed systems and database internals.",
    },
    {
        id: "j17",
        title: "Android Developer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Kotlin", "Android SDK", "Jetpack Compose"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "14 - 20 LPA",
        applyUrl: "#",
        description: "Enhance the food ordering experience for millions. Focus on app performance and smooth UI transitions.",
    },
    {
        id: "j18",
        title: "DevOps Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["AWS", "Docker", "Kubernetes"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "10 - 18 LPA",
        applyUrl: "#",
        description: "Manage CI/CD pipelines and cloud infrastructure. Ensure security and scalability of payments platform.",
    },
    {
        id: "j19",
        title: "Full Stack Developer",
        company: "Cognizant",
        location: "Kolkata",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Angular", "Node.js", "MongoDB"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "6 - 10 LPA",
        applyUrl: "#",
        description: "Full stack role for a healthcare client. Develop and maintain web portals.",
    },
    {
        id: "j20",
        title: "Data Engineer",
        company: "Fractal Analytics",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Spark", "Python", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "9 - 15 LPA",
        applyUrl: "#",
        description: "Build data pipelines for large scale analytics. Work with Fortune 500 clients.",
    },
    {
        id: "j21",
        title: "Support Engineer",
        company: "Salesforce",
        location: "Hyderabad",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["Apex", "CRM", "Troubleshooting"],
        source: "Company Site",
        postedDaysAgo: 4,
        salaryRange: "8 - 12 LPA",
        applyUrl: "#",
        description: "Provide technical support to Salesforce enterprise customers. Debug complex CRM issues.",
    },
    {
        id: "j22",
        title: "Cyber Security Analyst",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["SIEM", "Network Security", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12 - 18 LPA",
        applyUrl: "#",
        description: "Monitor and defend against security threats. Work in a state-of-the-art SOC.",
    },
    {
        id: "j23",
        title: "iOS Developer",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Swift", "iOS", "UIKit"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "15 - 22 LPA",
        applyUrl: "#",
        description: "Build the partner app for Urban Company professionals. Focus on reliability and offline-first usage.",
    },
    {
        id: "j24",
        title: "System Engineer",
        company: "Infosys",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1 Years",
        skills: ["Unix", "Scripting", "Java"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "3.6 - 5 LPA",
        applyUrl: "#",
        description: "Maintenance and support of legacy systems. Good stability and work-life balance.",
    },
    {
        id: "j25",
        title: "UI Developer",
        company: "Groww",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["React Native", "CSS", "Design Systems"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12 - 20 LPA",
        applyUrl: "#",
        description: "Build investment dashboards. Translate complex financial data into simple UI.",
    },
    {
        id: "j26",
        title: "Product Analyst",
        company: "Gojek",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["SQL", "Tableau", "Product Sense"],
        source: "Company Site",
        postedDaysAgo: 3,
        salaryRange: "14 - 24 LPA",
        applyUrl: "#",
        description: "Drive product decisions with data. Work closely with PMs and Engineering.",
    },
    {
        id: "j27",
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["Solidity", "Rust", "Web3.js"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "20 - 40 LPA",
        applyUrl: "#",
        description: "Build decentralized applications on Polygon. Deep understanding of EVM required.",
    },
    {
        id: "j28",
        title: "Technical Writer",
        company: "Postman",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Markdown", "API Documentation", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "8 - 15 LPA",
        applyUrl: "#",
        description: "Document APIs for millions of developers. Bridge the gap between code and humans.",
    },
    {
        id: "j29",
        title: "Network Engineer",
        company: "Cisco",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["CCNA", "Networking", "Python"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "10 - 16 LPA",
        applyUrl: "#",
        description: "Design and maintain enterprise networks. Work on next-gen routing protocols.",
    },
    {
        id: "j30",
        title: "Quality Analyst",
        company: "Mindtree",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Automation", "Java", "TestNG"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "5 - 9 LPA",
        applyUrl: "#",
        description: "Automate regression suites for banking client. Ensure defect-free releases.",
    },

    // 31-60: Mixed / Startup / Senior
    {
        id: "j31",
        title: "Senior SDE",
        company: "Amazon",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "5+ Years",
        skills: ["Java", "AWS", "System Design"],
        source: "Company Site",
        postedDaysAgo: 1,
        salaryRange: "40 - 70 LPA",
        applyUrl: "#",
        description: "Lead design of highly scalable systems for Amazon.com. Mentorship and technical leadership role.",
    },
    {
        id: "j32",
        title: "Frontend Lead",
        company: "MakeMyTrip",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "5+ Years",
        skills: ["React", "Performance", "Architecture"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "30 - 50 LPA",
        applyUrl: "#",
        description: "Architect the next generation booking flow. Optimize Core Vitals.",
    },
    {
        id: "j33",
        title: "Database Administrator",
        company: "Morgan Stanley",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5 Years",
        skills: ["DB2", "SQL", "Replication"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "20 - 35 LPA",
        applyUrl: "#",
        description: "Manage critical financial databases. Ensure compliance and disaster recovery.",
    },
    {
        id: "j34",
        title: "Golang Developer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5 Years",
        skills: ["Go", "Functional Programming", "Payments"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "25 - 45 LPA",
        applyUrl: "#",
        description: "Build payment infrastructure for India. Write pure functional code in production.",
    },
    {
        id: "j35",
        title: "SAP Consultant",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["ABAP", "SAP HANA", "Fiori"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "15 - 25 LPA",
        applyUrl: "#",
        description: "Implement SAP solutions for global clients. Travel opportunities available.",
    },
    {
        id: "j36",
        title: "Machine Learning Engineer",
        company: "Ola Electric",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5 Years",
        skills: ["Computer Vision", "Tensorflow", "C++"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "25 - 40 LPA",
        applyUrl: "#",
        description: "Work on autonomous driving tech for 2-wheelers. Deploy models to edge devices.",
    },
    {
        id: "j37",
        title: "Ruby on Rails Developer",
        company: "Chargebee",
        location: "Chennai",
        mode: "Remote",
        experience: "3-5 Years",
        skills: ["Ruby", "Rails", "SaaS"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "20 - 30 LPA",
        applyUrl: "#",
        description: "Build subscription management logic. Work on a global SaaS product.",
    },
    {
        id: "j38",
        title: "Product Manager",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5 Years",
        skills: ["Roadmap", "Analytics", "Growth"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "25 - 35 LPA",
        applyUrl: "#",
        description: "Lead the test prep category. Improve student retention and outcomes.",
    },
    {
        id: "j39",
        title: "Cloud Architect",
        company: "HCL Tech",
        location: "Noida",
        mode: "Hybrid",
        experience: "5+ Years",
        skills: ["Azure", "Terraform", "Security"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "20 - 30 LPA",
        applyUrl: "#",
        description: "Design cloud migration strategies. Consult with enterprise customers.",
    },
    {
        id: "j40",
        title: "Security Engineer",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["AppSec", "Pentesting", "Burp Suite"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "25 - 40 LPA",
        applyUrl: "#",
        description: "Secure the biggest e-commerce platform in India. Bug bounty exp valued.",
    },
    {
        id: "j41",
        title: "Embedded Systems Engineer",
        company: "Qualcomm",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5 Years",
        skills: ["C", "RTOS", "Linux Kernel"],
        source: "Company Site",
        postedDaysAgo: 2,
        salaryRange: "20 - 35 LPA",
        applyUrl: "#",
        description: "Work on Snapdragon chipsets. Low level driver development.",
    },
    {
        id: "j42",
        title: "Technical Lead",
        company: "Lenskart",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "5+ Years",
        skills: ["Node.js", "Microservices", "Team Leading"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "35 - 55 LPA",
        applyUrl: "#",
        description: "Lead the omnichannel tech team. Integrate online and offline store data.",
    },
    {
        id: "j43",
        title: "Big Data Developer",
        company: "Mu Sigma",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Hadoop", "Hive", "Python"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "8 - 12 LPA",
        applyUrl: "#",
        description: "Decision sciences and analytics. Work on large datasets.",
    },
    {
        id: "j44",
        title: "Game Developer",
        company: "Moonfrog",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Unity", "C#", "3D Math"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "12 - 20 LPA",
        applyUrl: "#",
        description: "Build casual mobile games played by millions. Optimization is key.",
    },
    {
        id: "j45",
        title: "Salesforce Developer",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["Apex", "LWC", "Salesforce Cloud"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "10 - 18 LPA",
        applyUrl: "#",
        description: "Salesforce implementation and customization. Certification preferred.",
    },
    {
        id: "j46",
        title: "RPA Developer",
        company: "UiPath",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["UiPath", ".NET", "Automation"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10 - 16 LPA",
        applyUrl: "#",
        description: "Build software robots to automate business processes.",
    },
    {
        id: "j47",
        title: "Full Stack Engineer",
        company: "Atlassian",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5 Years",
        skills: ["React", "Java", "GraphQL"],
        source: "Company Site",
        postedDaysAgo: 0,
        salaryRange: "30 - 50 LPA",
        applyUrl: "#",
        description: "Work on Jira and Confluence. World class engineering culture.",
    },
    {
        id: "j48",
        title: "Site Reliability Engineer",
        company: "LinkedIn",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["Python", "Linux", "Networking"],
        source: "Company Site",
        postedDaysAgo: 3,
        salaryRange: "35 - 55 LPA",
        applyUrl: "#",
        description: "Keep LinkedIn up and running. Incident management and capacity planning.",
    },
    {
        id: "j49",
        title: "Business Analyst",
        company: "McKinsey",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Excel", "PowerBI", "Consulting"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "14 - 20 LPA",
        applyUrl: "#",
        description: "Tech consulting for digital transformations. Strategic role.",
    },
    {
        id: "j50",
        title: "Flutter Developer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Dart", "Flutter", "Mobile"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "15 - 25 LPA",
        applyUrl: "#",
        description: "Build the world's largest fantasy sports app. Handle huge traffic spikes.",
    },
    {
        id: "j51",
        title: "Intern",
        company: "Goldman Sachs",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C++", "Java", "Algorithms"],
        source: "Company Site",
        postedDaysAgo: 4,
        salaryRange: "₹80,000/month",
        applyUrl: "#",
        description: "Summer analyst program. Work on high frequency trading systems.",
    },
    {
        id: "j52",
        title: "Support Specialist",
        company: "Dell",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1 Years",
        skills: ["Windows", "Hardware", "ServiceNow"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "3 - 5 LPA",
        applyUrl: "#",
        description: "IT support for enterprise customers. Night shifts may be required.",
    },
    {
        id: "j53",
        title: "PHP Developer",
        company: "Naukri.com",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["PHP", "Laravel", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "6 - 10 LPA",
        applyUrl: "#",
        description: "Maintain India's job portal. Optimize legacy codebases.",
    },
    {
        id: "j54",
        title: "React Developer",
        company: "Simpl",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5 Years",
        skills: ["React", "Checkout", "Payments"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "20 - 35 LPA",
        applyUrl: "#",
        description: "Build the 1-click checkout experience. High attention to detail needed.",
    },
    {
        id: "j55",
        title: "Systems Analyst",
        company: "Sonata Software",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["Requirements Gathering", "UML", "Agile"],
        source: "Indeed",
        postedDaysAgo: 8,
        salaryRange: "10 - 16 LPA",
        applyUrl: "#",
        description: "Bridge business requirements with technical implementation.",
    },
    {
        id: "j56",
        title: "Angular Developer",
        company: "UST Global",
        location: "Trivandrum",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["Angular", "RxJS", "Typescript"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "12 - 18 LPA",
        applyUrl: "#",
        description: "Frontend development for US retail client. Good work life balance.",
    },
    {
        id: "j57",
        title: "Junior Data Scientist",
        company: "Tiger Analytics",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["R", "Python", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "10 - 15 LPA",
        applyUrl: "#",
        description: "Predictive modeling and data mining. Work with seasoned data scientists.",
    },
    {
        id: "j58",
        title: "WordPress Developer",
        company: "Automattic",
        location: "Remote",
        mode: "Remote",
        experience: "3-5 Years",
        skills: ["PHP", "WordPress", "React"],
        source: "Company Site",
        postedDaysAgo: 1,
        salaryRange: "25 - 40 LPA",
        applyUrl: "#",
        description: "Work on WordPress.com VIP. Fully remote culture.",
    },
    {
        id: "j59",
        title: "Graphic Designer",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Illustrator", "Photoshop", "Social Media"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "6 - 10 LPA",
        applyUrl: "#",
        description: "Create engaging visuals for social media campaigns.",
    },
    {
        id: "j60",
        title: "CTO Office",
        company: "Oyo",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "0-1 Years",
        skills: ["Strategy", "Coding", "Generalist"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12 - 18 LPA",
        applyUrl: "#",
        description: "Program manager role in CTO office. diverse problem solving.",
    }
];
